F005 show salay by month
Flutter-2024/BTVN-Buoi-1 pull request #4
Opened 2024-01-08 10:48 UTC by NhuQuynhLea

# *SUMARY*
Calculate salary for NhanVienKinhDoanh.

# *CHANGE*
Change in some classes:
- Class NhanVienKinhDoanh: 
   - [x] Add new computed property thang.
- Class QuanLy:
   - [x] Add new function xemBangLuong.

# *CHECKLIST*
- [x] Enter month.
- [x] Show salaries of all employees by month.
- [x] Reformat code with dart format.

# *RESULT*
![image]()

2024-01-08 14:36 UTC, VuNA2k2 approved these changes

2024-01-08 16:12 UTC, Tris1702 approved these changes

2024-01-08 16:15 UTC, VuNA2k2 requested changes

2024-01-08 16:15 UTC, VuNA2k2 commented on NhanVien.dart
> +      required this.luong });
Don't change necessary

2024-01-08 16:15 UTC, VuNA2k2 commented on NhanVienLapTrinh.dart
> +            luong: luong ) {
You should add "," at last element of args

2024-01-08 16:15 UTC, VuNA2k2 commented on QuanLy.dart
> +    var quanLyLuong = QuanLyThangLuong(dsNV: dsNV, thang: thang!);
You must check whether var is null before using the force not null operation.

2024-01-09 03:29 UTC, VuNA2k2 approved these changes

2024-01-09 04:14 UTC, merged