F002 add edit remove employee information
Flutter-2024/BTVN-Buoi-1 pull request #5
Opened 2024-01-08 17:01 UTC by Linhmyx1512

2024-01-08 17:21 UTC, Tris1702 reviewed
Revert all change is not necessary

2024-01-08 17:21 UTC, Tris1702 commented on NhanVien.dart
> +  NhanVien({required this.hoTen,
Revert

2024-01-08 17:21 UTC, Tris1702 commented on NhanVien.dart
> +
Revert

2024-01-08 17:21 UTC, Tris1702 commented on NhanVienKinhDoanh.dart
> -  NhanVienKinhDoanh(
Revert

2024-01-08 17:21 UTC, Tris1702 commented on NhanVienLapTrinh.dart
> -  NhanVienLapTrinh(
Revert

2024-01-08 17:21 UTC, Tris1702 commented on README.md
> -# BTVN-Buoi-1
Revert

2024-01-08 17:30 UTC, Linhmyx1512 commented on NhanVien.dart
> +  NhanVien({required this.hoTen,
I reverted.

2024-01-09 02:07 UTC, Tris1702 requested changes

2024-01-09 02:07 UTC, Tris1702 commented on QuanLy.dart
> +      while (int.tryParse(choice!) == null) {
are you sure `choice` always `!= null` ?

2024-01-09 02:07 UTC, Tris1702 commented on QuanLy.dart
> +    while (int.tryParse(loaiNV!) == null) {
same question above

2024-01-09 02:07 UTC, Tris1702 commented on QuanLy.dart
> +          hoTen: hoTen!,
same question above

2024-01-09 02:07 UTC, Tris1702 commented on QuanLy.dart
> +      while (int.tryParse(choice!) == null) {
research more about null safety

2024-01-09 17:05 UTC, Tris1702 approved these changes

2024-01-09 18:06 UTC, merged